outsource the configuration in a distinct file

diff --git a/peep b/peep
--- a/peep
+++ b/peep
@@ -1,23 +1,22 @@
 #!/usr/bin/env bash
 # SYNOPSIS  peep is a super simple note management tool for the Bash command line
 # AUTHOR    Christopher Engelmann
-
-# configurable by the user
-# ------------------------
-  printing_tool=less
-  editor=vim
-  editor_opt='"+set nonumber"'
-  path_notes=~/.peep
-# ------------------------
-# TODO separate this into a gitignored file & make it editable by the cmd
+# URL       https://github.com/webcitizen-de/peep
 
 instdir=$(dirname $BASH_SOURCE)
 script_name=$(basename $BASH_SOURCE)
 script_path="$instdir/$script_name"
+config_file="peep.config"
 [[ ! -f $path_notes/.trash ]] && mkdir "$path_notes/.trash"
 
-clear
+if [[ -f $config_file ]]; then
+    source "$config_file"
+else
+    echo "Error. Missing configuration file '$config_file'"
+    exit 1
+fi
 
+clear
 
 function create_file() {
 
@@ -33,7 +32,7 @@ function create_file() {
 function print_help() {
 
     echo "Syntax: peep [ [e|edit] [d|delete] ] NOTENAME"
-    echo "        peep notes | [empty] trash | code"
+    echo "        peep notes | [empty] trash | config"
     echo
     echo "Create a new note just type:  peep YOUR_NOTENAME"
     echo "Edit a existing file:         peep e YOUR_NOTENAME  OR  peep edit YOUR_NOTENAME"
@@ -43,7 +42,7 @@ function print_help() {
     echo "Show the notes in trash:      peep trash"
     echo "Empty the trash:              peep empty trash"
     echo
-    echo "Edit the source code of peep: peep code"
+    echo "Edit the configuration:       peep config"
     echo
 }
 
@@ -52,8 +51,8 @@ function print_help() {
 parameters="$1 $2"
 
 case "$parameters" in
-    "code ")
-        eval $editor "$script_path"
+    "config ")
+        eval "$editor" "$config_file"
     ;;
 
     "d "*|"delete "*)
